"""add github_connections

Revision ID: 705784e1396b
Revises: 
Create Date: 2026-04-29 00:28:54.704269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705784e1396b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('encrypted_token', sa.String(length=512), nullable=False),
    sa.Column('tracked_repos', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_github_connections_user_id')
    )
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=False),
    sa.Column('window', sa.JSON(), nullable=False),
    sa.Column('aggregated', sa.JSON(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_snapshots_repo'), 'metrics_snapshots', ['repo'], unique=False)
    op.create_table('terraform_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('paths', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terraform_snapshots_repo'), 'terraform_snapshots', ['repo'], unique=False)
    op.create_index(op.f('ix_terraform_snapshots_sha'), 'terraform_snapshots', ['sha'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', 'repo', 'event_type', name='uq_delivery_repo_event')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=False),
    sa.Column('terraform_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('metrics_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'suggestion_ready', 'pr_opened', 'failed', name='runstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('suggested_config', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metrics_snapshot_id'], ['metrics_snapshots.id'], ),
    sa.ForeignKeyConstraint(['terraform_snapshot_id'], ['terraform_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_repo'), 'optimization_runs', ['repo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_runs_repo'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_terraform_snapshots_sha'), table_name='terraform_snapshots')
    op.drop_index(op.f('ix_terraform_snapshots_repo'), table_name='terraform_snapshots')
    op.drop_table('terraform_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_repo'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_table('github_connections')
    # ### end Alembic commands ###
